### ISSUE TITLE
Moving contigs/genomes with drag&drop

### ISSUE THREAD

**Issue by nterhoeven** [AliTVTeam/AliTV#105]
It would be nice, to move contigs (left-rigth) and genomes (up-down) using drag & drop functionality

**Comment by iimog** [comment]
Thanks for the input. We were discussing the implementation of this feature as well. It seems to be the most intuitive way to perform this kind of user interaction. What kept us from implementing it was the fact that performance does not allow dynamic redrawing of the image during the drag&drop event. Further dragging the mouse is already the interaction for zooming.

However it might be possible to handle drag events that originate from sequences differently and visualize the event with a simple stylized box rather than fully redrawing. We'll keep this on the agenda for the next major release.

**Comment by iimog** [comment]
Still agree it would be a nice feature but it is currently not planned to implement it.
